global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sales-notes'
    metrics_path: /metrics
    static_configs:
      - targets: ['sales-notes:3002']
        labels:
          env: 'local'
